#ifndef __DARAMCAM_MEDIAFOUNDATION_GENERATOR_H__
#define __DARAMCAM_MEDIAFOUNDATION_GENERATOR_H__

#include "DaramCam.h"

#ifndef	DARAMCAMMEDIAFOUNDATIONGENERATOR_EXPORTS
#define	DARAMCAMMEDIAFOUNDATIONGENERATOR_EXPORTS					__declspec(dllimport)
#else
#undef	DARAMCAMMEDIAFOUNDATIONGENERATOR_EXPORTS
#define	DARAMCAMMEDIAFOUNDATIONGENERATOR_EXPORTS					__declspec(dllexport)
#endif

enum {
	DCMFCONTAINER_MP4,
	DCMFCONTAINER_ADTS,
};

enum {
	DCMFVF_H264,
};

enum {
	DCMFAF_AAC,
};

enum {
	DCMFVF_FRAMETICK_60FPS = 16,
	DCMFVF_FRAMETICK_30FPS = 33,
	DCMFVF_FRAMETICK_24FPS = 41
};

DARAMCAMMEDIAFOUNDATIONGENERATOR_EXPORTS void DCMFStartup ();
DARAMCAMMEDIAFOUNDATIONGENERATOR_EXPORTS void DCMFShutdown ();

DARAMCAMMEDIAFOUNDATIONGENERATOR_EXPORTS DCVideoGenerator* DCCreateMFVideoGenerator ( DWORD containerFormat, DWORD videoFormat, unsigned frameTick );
DARAMCAMMEDIAFOUNDATIONGENERATOR_EXPORTS DCAudioGenerator* DCCreateMFAudioGenerator ( DWORD containerFormat, DWORD audioFormat );
DARAMCAMMEDIAFOUNDATIONGENERATOR_EXPORTS DCAudioVideoGenerator* DCCreateMFAudioVideoGenerator ( DWORD containerFormat, DWORD videoFormat, DWORD audioFormat, unsigned frameTick );


#endif